"""add 

  telegram fields to summary

Revision ID: 008143b48b22
Revises: efc32c8c8df9
Create Date: 2025-11-11 15:32:34.448235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '008143b48b22'
down_revision: Union[str, Sequence[str], None] = 'efc32c8c8df9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('summaries', 'sent_to_telegram',
               existing_type=sa.BOOLEAN(),
               comment='Si el resumen ya fue enviado al bot de Telegram',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('summaries', 'sent_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Timestamp de cuándo se envió a Telegram',
               existing_nullable=True)
    op.alter_column('summaries', 'telegram_message_ids',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='IDs de mensajes de Telegram donde se envió (formato: {chat_id: message_id})',
               existing_nullable=True)
    op.drop_index(op.f('idx_summaries_keywords'), table_name='summaries', postgresql_using='gin')
    op.drop_index(op.f('idx_summaries_text_fts'), table_name='summaries', postgresql_ops={'summary_text': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('idx_transcriptions_text_fts'), table_name='transcriptions', postgresql_ops={'text': 'gin_trgm_ops'}, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_transcriptions_text_fts'), 'transcriptions', ['text'], unique=False, postgresql_ops={'text': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('idx_summaries_text_fts'), 'summaries', ['summary_text'], unique=False, postgresql_ops={'summary_text': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('idx_summaries_keywords'), 'summaries', ['keywords'], unique=False, postgresql_using='gin')
    op.alter_column('summaries', 'telegram_message_ids',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='IDs de mensajes de Telegram donde se envió (formato: {chat_id: message_id})',
               existing_nullable=True)
    op.alter_column('summaries', 'sent_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp de cuándo se envió a Telegram',
               existing_nullable=True)
    op.alter_column('summaries', 'sent_to_telegram',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Si el resumen ya fue enviado al bot de Telegram',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###
