"""add users table for authentication

Revision ID: a0cb5968dd76
Revises: ca472a01716d
Create Date: 2025-11-17 10:02:31.003107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0cb5968dd76'
down_revision: Union[str, Sequence[str], None] = 'ca472a01716d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Primary key auto-incremental'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='Nombre de usuario único (usado para login)'),
    sa.Column('email', sa.String(length=100), nullable=False, comment='Email único del usuario'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='Contraseña hasheada con bcrypt (NUNCA almacenar plaintext)'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='Rol del usuario: admin, user, bot'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Indica si el usuario está activo (false = soft delete)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp de cuándo se creó el registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp de cuándo se modificó por última vez'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###

    # Crear usuario admin por defecto
    # Password: changeme123 (DEBE CAMBIARSE EN PRODUCCIÓN)
    # Hash generado con: bcrypt.hashpw(b"changeme123", bcrypt.gensalt())
    op.execute("""
        INSERT INTO users (username, email, hashed_password, role, is_active, created_at, updated_at)
        VALUES (
            'admin',
            'admin@localhost',
            '$2b$12$.pB9lm8nqtg.Tf2DvoXodOHMNwJ9X2EXjFbtbRD9nbdf3hjZ1U4Hi',
            'admin',
            true,
            NOW(),
            NOW()
        )
        ON CONFLICT (username) DO NOTHING;
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
