"""create sources and videos tables

Revision ID: a22c096070a4
Revises: 4781185b624b
Create Date: 2025-10-28 10:57:29.128640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a22c096070a4'
down_revision: Union[str, Sequence[str], None] = '4781185b624b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('name', sa.String(length=255), nullable=False, comment='Nombre de la fuente (ej: nombre del canal)'),
    sa.Column('url', sa.Text(), nullable=False, comment='URL de la fuente (canal YouTube, feed RSS, etc.)'),
    sa.Column('source_type', sa.String(length=50), nullable=False, comment="Tipo de fuente: 'youtube', 'rss', 'podcast'"),
    sa.Column('active', sa.Boolean(), nullable=False, comment='Si esta fuente está siendo monitoreada activamente'),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Metadatos adicionales (suscriptores, thumbnail, etc.)'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Clave primaria (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp de cuándo se creó el registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp de cuándo se modificó por última vez'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index('ix_sources_active', 'sources', ['active'], unique=False)
    op.create_index('ix_sources_source_type', 'sources', ['source_type'], unique=False)
    op.create_table('videos',
    sa.Column('source_id', sa.UUID(), nullable=False, comment='Clave foránea a la tabla sources'),
    sa.Column('youtube_id', sa.String(length=20), nullable=False, comment="ID del video de YouTube (ej: 'dQw4w9WgXcQ')"),
    sa.Column('title', sa.String(length=500), nullable=False, comment='Título del video desde YouTube'),
    sa.Column('url', sa.Text(), nullable=False, comment='URL completa del video de YouTube'),
    sa.Column('duration_seconds', sa.Integer(), nullable=True, comment='Duración del video en segundos (para estimar tiempo)'),
    sa.Column('status', sa.Enum('PENDING', 'DOWNLOADING', 'DOWNLOADED', 'TRANSCRIBING', 'TRANSCRIBED', 'SUMMARIZING', 'COMPLETED', 'FAILED', name='video_status', native_enum=False), nullable=False, comment='Estado actual del procesamiento en el pipeline'),
    sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), nullable=True, comment='Cuándo se publicó el video en YouTube'),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Metadatos adicionales (vistas, likes, thumbnail, etc.)'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Clave primaria (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp de cuándo se creó el registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp de cuándo se modificó por última vez'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('youtube_id')
    )
    op.create_index('ix_videos_published_at', 'videos', ['published_at'], unique=False)
    op.create_index('ix_videos_source_id', 'videos', ['source_id'], unique=False)
    op.create_index('ix_videos_source_status', 'videos', ['source_id', 'status'], unique=False)
    op.create_index('ix_videos_status', 'videos', ['status'], unique=False)
    op.create_index('ix_videos_youtube_id', 'videos', ['youtube_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_videos_youtube_id', table_name='videos')
    op.drop_index('ix_videos_status', table_name='videos')
    op.drop_index('ix_videos_source_status', table_name='videos')
    op.drop_index('ix_videos_source_id', table_name='videos')
    op.drop_index('ix_videos_published_at', table_name='videos')
    op.drop_table('videos')
    op.drop_index('ix_sources_source_type', table_name='sources')
    op.drop_index('ix_sources_active', table_name='sources')
    op.drop_table('sources')
    # ### end Alembic commands ###
