"""add bot_blocked field to telegram_users

Revision ID: ca472a01716d
Revises: 79dac5ed9f40
Create Date: 2025-11-13 13:17:32.803403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca472a01716d'
down_revision: Union[str, Sequence[str], None] = '79dac5ed9f40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_users', sa.Column('bot_blocked', sa.Boolean(), nullable=False, server_default=sa.text('false'), comment='Usuario ha bloqueado el bot o chat no existe'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telegram_users', 'bot_blocked')
    # ### end Alembic commands ###
